<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <ProduceReferenceAssembly>false</ProduceReferenceAssembly>
    <BaseOutputPath>Assembly\bin\</BaseOutputPath>
    <BaseIntermediateOutputPath>Assembly\obj\</BaseIntermediateOutputPath>
    <OutputPath>Assembly</OutputPath>
    <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
    <AppendRuntimeIdentifierToOutputPath>false</AppendRuntimeIdentifierToOutputPath>
    <AssemblyName>Scripts</AssemblyName>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Raylib-cs" Version="7.0.2" />
    <Reference Include="Scythe">
      <HintPath>/mnt/secondary/Projects/Scythe/bin/Debug/net10.0/Scythe.dll</HintPath>
    </Reference>
  </ItemGroup>
</Project>